language: cpp
os: linux
dist: bionic
compiler:
- gcc
- clang
arch:
- amd64
- arm64
- ppc64le
- s390x
jobs:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
  # clang does not find <shared_mutex> on trusty... so we skip this config!
  # - os: linux
  #   dist: trusty
  #   compiler: clang
  - os: linux
    dist: xenial
    compiler: gcc
  - os: linux
    dist: xenial
    compiler: clang
  - os: osx
    compiler: gcc
  - os: osx
    compiler: clang
install:
- git clone https://github.com/onqtam/doctest.git
- mkdir doctest/build
- cd doctest/build
- cmake -D DOCTEST_WITH_TESTS=OFF -D DOCTEST_WITH_MAIN_IN_STATIC_LIB=OFF -D CMAKE_BUILD_TYPE=Release ..
- sudo make -j2 install
- cd $TRAVIS_BUILD_DIR
- mkdir install
- cd install
- cmake ..
- sudo make -j2 install
- cd $TRAVIS_BUILD_DIR
script:
- mkdir build
- cd build
- cmake -D CMAKE_BUILD_TYPE=Debug ../tests
- make -j2
- ./tests