language: cpp
os: linux
dist: bionic
compiler:
- gcc
- clang
jobs:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      dist: trusty
      compiler: clang
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang
install:
- git clone https://github.com/onqtam/doctest.git
- mkdir -p doctest/build && cd doctest/build
- cmake ..
- sudo make -j4 install
script:
- mkdir -p build/install; mkdir build/tests
- cd build/install
- cmake ../..
- sudo make -j4 install
- cd ../tests
- cmake -D CMAKE_BUILD_TYPE=Release ../../tests
- make all test
- ctest --output-on-failure