language: cpp
os: linux
dist: bionic
compiler:
- gcc
- clang
jobs:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
  - os: linux
    dist: xenial
    compiler: gcc
  - os: linux
    dist: xenial
    compiler: clang
  - os: osx
    compiler: gcc
  - os: osx
    compiler: clang
install:
- git clone https://github.com/onqtam/doctest.git
- mkdir doctest/build
- cd doctest/build
- cmake ..
- sudo make -j4 install
- cd $TRAVIS_BUILD_DIR
- mkdir install
- cd install
- cmake ..
- sudo make -j4 install
- cd $TRAVIS_BUILD_DIR
script:
- mkdir build
- cd build
- cmake -D CMAKE_BUILD_TYPE=Release ../tests
- make -j4
- ctest --output-on-failure