name: All Platforms

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-12, macos-11, windows-2022, windows-2019]
        build_type: ['Release', 'Debug']
        cxx_std: [11, 14, 17, 20]

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake -B ${{github.workspace}}/build/${{matrix.build_type}} -DBUILD_TESTING=ON -DCMAKE_CXX_STANDARD=${{matrix.cxx_std}} -DCMAKE_INSTALL_PREFIX="${{github.workspace}}/install/${{matrix.build_type}}"

    - name: Build
      run: cmake --build ${{github.workspace}}/build/${{matrix.build_type}} --config ${{matrix.build_type}} --target install

    - name: Test
      env:
          CTEST_OUTPUT_ON_FAILURE: 1
      run: ctest --test-dir ${{github.workspace}}/build/${{matrix.build_type}}
